Translation.addTranslation("Lens", {ru: "Линза"});
Translation.addTranslation("Air", {ru: "Воздух"});
Translation.addTranslation("Nope", {ru: "Нет"});
Translation.addTranslation("Magic Table", {ru: "Магический Стол"});
Translation.addTranslation("Magic Pedestal", {ru: "Магический Пьедестал"});
Translation.addTranslation("Lens Of Air", {ru: "Линза Воздуха"});
Translation.addTranslation("Blood Diamond", {ru: "Кровавый Алмаз"});
Translation.addTranslation("The wind will push you up and when you attack the mobs, the wind will push them further away\n\nOn use no target: You fly up\nOn attack: The mob pushes further", {ru: "Ветер будет подталкивать вас вверх и когда вы будете нападать на мобов, ветер будет отталкивать их гораздо дальше\n\nПри удерживание: Вы взлетаете вверх\nПри атаке: Моб отталкивается дальше"});
Translation.addTranslation("Fire", {ru: "Огонь"});
Translation.addTranslation("Lens Of Fire", {ru: "Линза Огня"});
Translation.addTranslation("Blood", {ru: "Кровь"});
Translation.addTranslation("Lens Of Blood", {ru: "Линза Крови"});
Translation.addTranslation("Magic Wand", {ru: "Магическая Палочка"});
Translation.addTranslation("Description", {ru: "Описание"});
Translation.addTranslation("Launches fireballs and sets fire to blocks\n\nOn use no target: Launch fareball\nOn use: Set fire", {ru: "Запускает огненные шары, а так же поджигает блоки\n\nПри удерживание: Запускает огненный шар\nПри использование: Поджигает блок"});
Translation.addTranslation("Restores health through target health\n\nWhen using on a mob: Inflicts 1hp to a mob and restore 1hp you\nOn use no target: If a diamond lies nearby, it replaces it with a bloody one and takes 19hp from you", {ru: "Восполняет здоровье за счёт здоровья цели\n\nПри использование на мобе: Наносит 1hp урона мобу и восполняет 1hp вам\nПри использование без цели: Если рядом лежит алмаз, то заменяет его на кровавый и отнимает у вас 19hp"});
Translation.addTranslation("Lens Of Telekinesis", {ru: "Линза Телекинеза"});
Translation.addTranslation("Telekinesis", {ru: "Телекинез"});
Translation.addTranslation("Allows you to lift mobs into the air and throw them far\n\nWhen using on a mob: raise mob\nLeft top button using for throw mob\nLeft down button using for let off mob", {ru: "Позволит вам поднимать мобов в воздух и далеко кидать их\n\nПри использование на мобе: Поднимает его\nЛевая верхняя кнопка бросает моба\nЛевая нижняя кнопка отпускает моба"});
Translation.addTranslation("Empty Lens", { ru: "Пустая Линза" });
Translation.addTranslation("Nature", { ru: "Природа" });
Translation.addTranslation("Lens Of Nature", { ru: "Линза Природы" });
Translation.addTranslation("Nature lens active", { ru: "Линза природы активна" });